languages = ['Ruby', 'C', 'C++', 'Python']
print(languages)
languages.append('Scheme')
print(languages)
print(sorted(languages))
print(languages)
languages.remove('Scheme')
print(languages)
languages.insert(1, 'Java')
print(languages)
languages.reverse()
print(languages)
languages.reverse()
print(languages)
del languages[0]
print(languages)
print(sorted(languages, reverse=True))
print(languages)
languages.pop()
languages.pop()
print(languages)
languages.pop()
languages.pop()
print(languages)
