places = ['Xizang', 'London', 'ZheJiang', 'Paris', 'Switzerland']
print(places)
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
